import type { UIConfig } from 'utils/Configs';
import { icon } from '@fortawesome/fontawesome-svg-core/import.macro';

const SarvasvaBedroomConfigs: UIConfig = {
  id: 124,
  screenOff: '74',
  crestronConfigs: {
    host: '10.21.21.203',
    ipID: 19,
    port: 41794,
  },
  layout: {
    bodyColor: '#ecf0f1',
    foregroundColor: '#ecf0f1',
    navColor: '#2c3e50',
  },
  pages: {
    LIGHTS: {
      name: 'Lights',
      icon: icon({ name: 'lightbulb' }),
      controls: {
        off: {
          kind: 'toggle',
          icon: icon({ name: 'power-off' }),
          title: 'Lights',
          label: 'All On/Off',
          state: '1',
          stateOff: '20',
          intensityStates: [
            { state: '6', stateOff: '1', name: 'Medium' },
            { state: '7', stateOff: '1', name: 'Low' },
          ], // ['5', '6', '7'],
        },
        scene2: {
          kind: 'toggle',
          icon: icon({ name: 'bed' }),
          title: 'Lights',
          label: 'Shayan',
          state: '2',
          stateOff: '20',
          intensityStates: [
            { state: '12', stateOff: '2', name: 'Low' },
            { state: '13', stateOff: '2', name: 'High' },
          ], // ['11', '12', '13'],
        },
        scene3: {
          kind: 'toggle',
          icon: icon({ name: 'lightbulb' }),
          title: 'Lights',
          label: 'Akshardham',
          state: '3',
          stateOff: '20',
          intensityStates: [
            { state: '9', stateOff: '3', name: 'Medium' },
            { state: '10', stateOff: '3', name: 'Low' },
          ], // ['8', '9', '10'],
        },
        scene4: {
          kind: 'toggle',
          icon: icon({ name: 'moon' }),
          title: 'Lights',
          label: 'Night Lights',
          state: '27',
          stateOff: '19',
          intensityStates: [
            { state: '28', stateOff: '27', name: 'Medium' },
            { state: '29', stateOff: '27', name: 'High' },
          ],
        },
      },
    },
    HVAC: {
      name: 'HVAC',
      icon: icon({ name: 'fan' }),
      controls: {
        temperature: {
          kind: 'temperature',
        },
      },
    },
    SOURCE: {
      name: 'Audio',
      icon: icon({ name: 'music' }),
      controls: {
        bedroom: {
          kind: 'audio',
          icon: icon({ name: 'tent' }),
          label: 'Bedroom',
          play: '46',
          pause: '45',
          toggle: '44',
          lock: '43',
          levelDown: '42',
          levelUp: '41',
          state: '31',
          playLabel: 'Unmute',
          pauseLabel: 'Mute',
        },
        bathroom: {
          kind: 'audio',
          icon: icon({ name: 'tent' }),
          label: 'Bathroom',
          play: '58',
          pause: '57',
          toggle: '56',
          lock: '43',
          levelDown: '54',
          levelUp: '53',
          state: '33',
          playLabel: 'Unmute',
          pauseLabel: 'Mute',
        },
        microphone: {
          kind: 'audio',
          icon: icon({ name: 'tent' }),
          label: 'Mic',
          play: '52',
          pause: '51',
          toggle: '50',
          lock: '43',
          levelDown: '48',
          levelUp: '47',
          state: '32',
          playLabel: 'Unmute',
          pauseLabel: 'Mute',
        },
        bluetooth: {
          kind: 'toggle',
          icon: icon({ name: 'signal' }),
          title: 'Source',
          label: 'Bluetooth',
          state: '31',
        },
        mandir: {
          kind: 'toggle',
          icon: icon({ name: 'om' }),
          title: 'Source',
          label: 'Mandir',
          state: '32',
        },
        pramukhhall: {
          kind: 'toggle',
          icon: icon({ name: 'people-roof' }),
          title: 'Source',
          label: 'Sabha Hall',
          state: '33',
        },
        event: {
          kind: 'toggle',
          title: 'Source',
          icon: icon({ name: 'tent' }),
          label: 'Event Tent',
          state: '34',
        },
        mic: {
          kind: 'toggle',
          title: 'Source',
          icon: icon({ name: 'microphone-lines' }),
          label: 'Mic',
          state: '35',
        },
      },
    },
    VIDEO: {
      name: 'Video',
      icon: icon({ name: 'video' }),
      controls: {
        mandir: {
          kind: 'toggle',
          icon: icon({ name: 'om' }),
          title: 'Source',
          label: 'Mandir',
          state: '21',
        },
        pramukhhall: {
          kind: 'toggle',
          icon: icon({ name: 'people-roof' }),
          title: 'Source',
          label: 'Sabha Hall',
          state: '22',
        },
        event: {
          kind: 'toggle',
          title: 'Source',
          icon: icon({ name: 'tent' }),
          label: 'Event Tent',
          state: '23',
        },
        site: {
          kind: 'toggle',
          title: 'Source',
          icon: icon({ name: 'helmet-safety' }),
          label: 'Akshardham Site',
          state: '24',
        },
      },
    },
  },
};

export default SarvasvaBedroomConfigs;
