import type { UIConfig } from 'utils/Configs';
import { icon } from '@fortawesome/fontawesome-svg-core/import.macro';

const StudioConfigs: UIConfig = {
  crestronConfigs: {
    host: '10.21.166.7',
    ipID: 10,
    port: 41794,
  },
  layout: {
    bodyColor: '#ecf0f1',
    foregroundColor: '#ecf0f1',
    navColor: '#2c3e50',
  },
  pages: {
    LIVE: {
      code: '4320A',
      name: 'Live',
      icon: icon({ name: 'clapperboard' }),
      controls: {
        downZ1: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Down Z1',
          state: '17',
          stateOff: '18',
          analogFeedback: '1',
        },
        downZ2: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Down Z2',
          state: '19',
          stateOff: '20',
          analogFeedback: '2',
        },
        cove: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Cove',
          state: '21',
          stateOff: '22',
          analogFeedback: '3',
        },
      },
    },
    ISO: {
      code: '4320C',
      name: 'ISO',
      icon: icon({ name: 'microphone' }),
      controls: {
        down: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Down',
          state: '23',
          stateOff: '24',
          analogFeedback: '10',
        },
        cove: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Cove',
          state: '25',
          stateOff: '26',
          analogFeedback: '11',
        },
      },
    },
    AUDIO: {
      code: '4320B',
      name: 'Audio Control',
      icon: icon({ name: 'volume-low' }),
      controls: {
        downZ1: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Down Z1',
          state: '7',
          stateOff: '8',
          analogFeedback: '4',
        },
        downZ2: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Down Z2',
          state: '9',
          stateOff: '10',
          analogFeedback: '5',
        },
        downZ3: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Down Z3',
          state: '11',
          stateOff: '12',
          analogFeedback: '19',
        },
        coveZ1: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Cove Z1',
          state: '13',
          stateOff: '14',
          analogFeedback: '6',
        },
        coveZ2: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Cove Z2',
          state: '15',
          stateOff: '16',
          analogFeedback: '7',
        },
        isoGlass: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'ISO Glass',
          state: '35',
          stateOff: '36',
          analogFeedback: '8',
          inverted: true,
        },
        liveGlass: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Live Glass',
          state: '37',
          stateOff: '38',
          analogFeedback: '9',
          inverted: true,
        },
        status: {
          kind: 'light',
          icon: icon({ name: 'circle' }),
          label: 'On Air',
          state: '39',
          stateOff: '40',
        },
      },
    },
    VIDEO: {
      code: '4320D',
      name: 'Video Control',
      icon: icon({ name: 'video' }),
      controls: {
        downZ1: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Down Z1',
          state: '1',
          stateOff: '2',
          analogFeedback: '16',
        },
        downZ2: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Down Z2',
          state: '3',
          stateOff: '4',
          analogFeedback: '17',
        },
        cove: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Cove',
          state: '5',
          stateOff: '6',
          analogFeedback: '18',
        },
      },
    },
    SL: {
      name: 'SL 1&2',
      icon: icon({ name: 'bold' }),
      controls: {
        downZ1: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Down SL1',
          state: '27',
          stateOff: '28',
          analogFeedback: '12',
        },
        coveZ1: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Cove SL1',
          state: '29',
          stateOff: '30',
          analogFeedback: '14',
        },
        downZ2: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Down SL2',
          state: '31',
          stateOff: '32',
          analogFeedback: '13',
        },
        coveZ2: {
          kind: 'light',
          icon: icon({ name: 'lightbulb' }),
          label: 'Cove SL2',
          state: '33',
          stateOff: '34',
          analogFeedback: '15',
        },
      },
    },
  },
};

export default StudioConfigs;
